### ISSUE TITLE
Push tags

### ISSUE THREAD

**Issue by pawamoy** [andrew-d/python-multipart#25]
There's a discrepancy between released versions on PyPI (0.0.1 through 0.0.5) and tags on GitHub (0.0.2 and 0.0.4 only). Could you push the tags onto this repository 🙂 ? It can be confusing when checking what the latest version is, etc.

**Comment by FFY00** [comment]
Second that, I am packaging this for Arch Linux and would really appreciate if you pushed them. Thanks!

**Comment by andrew-d** [comment]
Whoops, sorry folks - had my filters set up very incorrectly and missed this! Just pushed the tag 0.0.5 now.

I'm afraid that I don't actually know what commits were used to publish versions 0.0.1 or 0.0.3 - if this matters, I'm happy to try and reverse-engineer based on the contents of the PyPI packages?

**Comment by pawamoy** [comment]
Thanks! Well sure why not! The commit and release dates should help greatly :)

**Comment by Kludex** [comment]
@pawamoy is this still needed?

**Comment by pawamoy** [comment]
It's a nice thing to have, though I personally don't need it anymore.
