### ISSUE TITLE
Fails with FastAPI 0.63.x Python 3.9.7

### ISSUE THREAD

**Issue by svanschalkwyk** [andrew-d/python-multipart#45]
"No module named multipart" or "No module named python_multipart".
If imports are removed, then 
```
Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 
pip install python-multipart
```

**Comment by tomchristie** [comment]
Not clear exactly what your issue is from that description, but it's not an issue with the `python-multipart` package itself.
