### ISSUE TITLE
DEPRECATION: python-multipart is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by fenchu** [andrew-d/python-multipart#50]
```
DEPRECATION: python-multipart is being installed using the legacy 'setup.py install' method, 
because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 
will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. 
Discussion can be found at https://github.com/pypa/pip/issues/8559
```
https://github.com/pypa/pip/issues/8559
python-multipart==0.0.5

**Comment by johnthagen** [comment]
Related to:

- #37

**Comment by Kludex** [comment]
Does anyone use `python-multipart` besides with Starlette/FastAPI? Please let me know.

**Comment by johnthagen** [comment]
Maybe Django Rest Framework?

**Comment by johnthagen** [comment]
FastAPI is the biggest project I know of:

- https://github.com/tiangolo/fastapi/blob/18d087f9c66b06c8baa4164bdf647af362b4a4ee/fastapi/dependencies/utils.py#L78
- https://fastapi.tiangolo.com/tutorial/request-files/#request-files

**Comment by johnthagen** [comment]
Flask/werkzeug seems to have their own as well

- https://github.com/pallets/werkzeug/blob/a3005e6acda7246fe0a684c71921bf4882b4ba1c/src/werkzeug/formparser.py#L340
- https://github.com/pallets/werkzeug/blob/main/src/werkzeug/sansio/multipart.py#L79

**Comment by johnthagen** [comment]
> My question is to know if we need to make a bigger effort to get the python-multipart PyPI name, so it can benefit other packages that are using python-multipart.

GitHub dependency graph has some numbers:

- https://github.com/andrew-d/python-multipart/network/dependents
- https://github.com/andrew-d/python-multipart/network/dependents?dependent_type=PACKAGE

Seems to be used by a large number of users, but sometimes there are false positives. Also many of them might simply have a transitive dependency on Starlette.

**Comment by Kludex** [comment]
I just got rights from @andrew-d.

I'm going to make a release this week. 👍
