### ISSUE TITLE
multipart.File has no MIME type information

### ISSUE THREAD

**Issue by srittau** [andrew-d/python-multipart#58]
Unfortunately, multipart's `File` class seems to have a serious regression compared to cgi's `FieldStorage` class: Where `FieldStorage.type` contained the declared MIME type of the uploaded file (or `None` if not given), `File` does not seem to have this information. This makes is basically impossible to download uploaded files while keeping the file type intact.

**Comment by srittau** [comment]
Sorry, I meant to file this with Ariadne.

**Comment by rafalp** [comment]
@srittau this is valid feature requirement for python-multipart, which is Ariadne's dependency for files upload. Please reopen.

**Comment by Kludex** [comment]
PR welcome.

**Comment by Kludex** [comment]
- Closed by https://github.com/Kludex/python-multipart/pull/143
