### ISSUE TITLE
Generalize install instructions for other shells

### ISSUE THREAD

**Issue by eltbus** [andrew-d/python-multipart#69]
**Error** when running `pip install .[dev]` on zsh, because `[` and `]` are special characters.
```
pip install .[dev]
zsh: no matches found: .[dev]
```

**Solution** (from [this issue](https://github.com/mu-editor/mu/issues/852)) is to use quotes
```
pip install '.[dev]'
```

Please consider updating the README

**Comment by Kludex** [comment]
PR welcome. 👀

**Comment by eltbus** [comment]
Merged https://github.com/andrew-d/python-multipart/pull/71
